//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanNet.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string IdHoaDon { get; set; }
        public System.DateTime NgayXuatHD { get; set; }
        public string IdTK { get; set; }
        public string IdChiTiet { get; set; }
    
        public virtual HoaDonChiTiet HoaDonChiTiet { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
