//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanNet.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListTPham
    {
        public string IdOrderList { get; set; }
        public string IdTP { get; set; }
        public int SoluongTP { get; set; }
        public int ThanhTien { get; set; }
        public string IdChiTiet { get; set; }
    
        public virtual HoaDonChiTiet HoaDonChiTiet { get; set; }
        public virtual TPham TPham { get; set; }
    }
}
