//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanNet.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPham()
        {
            this.ListTPhams = new HashSet<ListTPham>();
        }
    
        public string IdTP { get; set; }
        public string TenTP { get; set; }
        public int Gia { get; set; }
        public string IdLoaiTP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListTPham> ListTPhams { get; set; }
        public virtual LoaiTPham LoaiTPham { get; set; }
    }
}
